### ISSUE TITLE
Customize gitignore for Flask and Django

### ISSUE THREAD

**Issue by Lyasinkovska** [mehalyna/Ch-117-Python-Project-ITA#30]
Create gitignore file and fill it in with untracked files to ignore according to the current project (Python, Flask, Django).

**Comment by dmytro-terletskyi** [comment]
The [gitignore file](https://github.com/mehalyna/Ch-117-Python-Project-ITA/blob/developer/.gitignore) is already customized for Flask and Django (see lines 58 and 64).
